version: '3'

services:
  app:
    container_name: app
    depends_on:
      - mongo
    image: scaffold-web
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile
    env_file: docker.env
    ports:
      - 80:3000
    volumes:
      - $PWD/.uploads:/opt/scaffold-files
    networks:
      - scaffold-net
  mongo:
    container_name: mongo
    command:
      - --storageEngine=wiredTiger
    image: mongo:4.2.5-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: t41t0m05
    volumes:
      - $PWD/data:/data/db
      - $PWD/database:/opt/database
    networks:
      - scaffold-net
  crontab:
    container_name: crontab
    image: crontab
    privileged: true
    restart: always
    depends_on:
      - app
    build:
      context: .
      dockerfile: cron-dockerfile
    volumes:
      - ./backups:/opt/backups
    networks:
      - scaffold-net
networks:
  scaffold-net:
